- name: Demo on Conditions
  hosts: localhost
  tasks:
    - name: Print Unix
      ansible.builtin.debug:
        msg: Hello, Unix
      when: os_name == "unix"

    - name: Print linux
      ansible.builtin.debug:
        msg: Hello, Linux
      when: os_name == "linux"